"""Explicit typing contracts for the bot mixin composition points."""

from __future__ import annotations

import threading
from concurrent.futures import ThreadPoolExecutor
from typing import TYPE_CHECKING

import telebot
from telebot import types

from config import ConfigLike
from core import Subscription
from loggers import Logger
__all__ = ["AdminFeatureMixin", "PublicFeatureMixin"]


if TYPE_CHECKING:
    class AdminFeatureMixin:
        bot: telebot.TeleBot
        log: Logger
        cfg: ConfigLike
        lang_cfg: ConfigLike
        sub: Subscription
        USERS_PER_PAGE: int
        admin_uids: list[int]
        polling_thread: threading.Thread | None
        _pending_codes: dict[str | int, str]
        _pending_edits: dict[int, dict[str, str]]
        _pagination_state: dict[int, dict[str, int]]
        _pending_leaderboard: dict[int, dict[str, str | int]]

        def _send_message(self, chat_id: int, text: str, **kwargs: object) -> None: ...
        def _delete_message(self, chat_id: int, message_id: int, *, secret: bool = False) -> None: ...
        def get_main_menu(self) -> types.InlineKeyboardMarkup: ...
        def get_codes_menu(self) -> types.InlineKeyboardMarkup: ...
        def get_users_menu(self, prefix: str, page: int = 0) -> types.InlineKeyboardMarkup: ...
        def _cb_online_users(self, chat_id: int) -> None: ...
        def _cb_list_users(self, chat_id: int, page: int = 0) -> None: ...
        def _cb_refresh(self, chat_id: int) -> None: ...
        def _step_reset_user(self, message: types.Message) -> None: ...
        def _step_add_user_name(self, message: types.Message) -> None: ...
        def _cb_info_user(self, chat_id: int, username: str) -> None: ...
        def _cb_del_user(self, chat_id: int, username: str) -> None: ...
        def _cb_list_codes(self, chat_id: int) -> None: ...
        def _step_info_code(self, message: types.Message) -> None: ...
        def _step_del_code(self, message: types.Message) -> None: ...
        def _step_add_code_name(self, message: types.Message) -> None: ...
        def _cb_all_panels_status(self, chat_id: int) -> None: ...
        def _step_add_code_days(self, message: types.Message, code_type: str, code_name: str) -> None: ...
        def _step_chart_username(self, message: types.Message) -> None: ...
        def _cb_leaderboard_type(self, chat_id: int) -> None: ...
        def _cb_edit_user_options(self, chat_id: int, username: str) -> None: ...
        def _cb_edit_fingerprint(self, chat_id: int, username: str) -> None: ...
        def _cb_edit_limit(self, chat_id: int, username: str) -> None: ...
        def _cb_edit_wl_limit(self, chat_id: int, username: str) -> None: ...
        def _cb_edit_time(self, chat_id: int, username: str) -> None: ...
        def _cb_edit_name(self, chat_id: int, username: str) -> None: ...
        def _cb_leaderboard_order(self, chat_id: int) -> None: ...
        def _cb_leaderboard_window(self, chat_id: int) -> None: ...

    class PublicFeatureMixin:
        bot: telebot.TeleBot
        log: Logger
        cfg: ConfigLike
        lang_cfg: ConfigLike
        sub: Subscription
        TEXTS: dict[str, dict[str, str]]
        polling_thread: threading.Thread | None
        _executor: ThreadPoolExecutor

        def _send_message(self, chat_id: int, text: str, **kwargs: object) -> None: ...
        def _delete_message(self, chat_id: int, message_id: int, *, secret: bool = False) -> None: ...
        def get_lang(self, uid: int) -> str: ...
        def get_menu(self, uid: int) -> types.ReplyKeyboardMarkup: ...
        def cmd_start(self, message: types.Message) -> None: ...
        def send_info(self, chat_id: int, uid: int, lang: str) -> None: ...
        def send_link(self, chat_id: int, uid: int, lang: str) -> None: ...
        def step_bonus(self, message: types.Message) -> None: ...
        def step_reset(self, message: types.Message) -> None: ...
        def step_delete(self, message: types.Message) -> None: ...
else:
    class AdminFeatureMixin:
        """Runtime-neutral base for administrator feature mixins."""

    class PublicFeatureMixin:
        """Runtime-neutral base for public feature mixins."""


