from __future__ import annotations

from typing import TYPE_CHECKING

from config import ConfigLike
from loggers import Logger

__all__ = ["PublicFeatureMixin"]


if TYPE_CHECKING:
    import asyncio

    import discord

    from sessions import SessionStore
    from webapi import ApiResult, WebApiClient

    class PublicFeatureMixin:
        bot: discord.Client
        log: Logger
        cfg: ConfigLike
        lang_cfg: ConfigLike
        http: WebApiClient
        sessions: SessionStore
        TEXTS: dict[str, dict[str, str]]
        _chart_locks: dict[int, asyncio.Lock]
        _chart_busy: set[int]

        def get_lang(self, user_id: int) -> str: ...
        def has_lang(self, user_id: int) -> bool: ...
        def is_logged_in(self, user_id: int) -> bool: ...
        def text(self, lang: str, key: str, **kwargs: object) -> str | None: ...
        def modal_values(self, interaction: discord.Interaction) -> dict[str, str]: ...
        def in_dm(self, interaction: discord.Interaction) -> bool: ...
        def language_view(self) -> discord.ui.View: ...
        def main_menu_view(self, lang: str, *, logged_in: bool) -> discord.ui.View: ...
        def subscription_menu_view(self, lang: str) -> discord.ui.View: ...
        def account_menu_view(self, lang: str) -> discord.ui.View: ...
        def confirm_view(self, lang: str, action: str) -> discord.ui.View: ...
        def settings_menu_view(self, lang: str) -> discord.ui.View: ...
        def chart_view(self, lang: str) -> discord.ui.View: ...
        async def require_login(self, interaction: discord.Interaction) -> bool: ...
        async def _respond(
            self,
            interaction: discord.Interaction,
            content: str | None,
            *,
            ephemeral: bool | None = None,
            view: discord.ui.View | None = None,
            file: discord.File | None = None,
        ) -> None: ...
        async def _reply_key(
            self,
            interaction: discord.Interaction,
            key: str,
            *,
            ephemeral: bool | None = None,
            view: discord.ui.View | None = None,
            file: discord.File | None = None,
            **fmt: object,
        ) -> None: ...
        async def _defer(self, interaction: discord.Interaction, *, ephemeral: bool | None = None) -> None: ...
        def apply_api_status(self, user_id: int, result: ApiResult) -> str | None: ...
        async def consume_result(self, interaction: discord.Interaction, result: ApiResult) -> bool: ...
        async def cmd_start(self, interaction: discord.Interaction) -> None: ...
        async def cmd_support(self, interaction: discord.Interaction) -> None: ...
        async def cmd_login(self, interaction: discord.Interaction) -> None: ...
        async def cmd_register(self, interaction: discord.Interaction) -> None: ...
        async def cmd_info(self, interaction: discord.Interaction) -> None: ...
        async def cmd_sub(self, interaction: discord.Interaction) -> None: ...
        async def cmd_bonus(self, interaction: discord.Interaction) -> None: ...
        async def cmd_chart(self, interaction: discord.Interaction) -> None: ...
        async def cmd_settings(self, interaction: discord.Interaction) -> None: ...
        async def cmd_help(self, interaction: discord.Interaction) -> None: ...
        async def cmd_logout(self, interaction: discord.Interaction) -> None: ...
        async def cmd_reset(self, interaction: discord.Interaction) -> None: ...
        async def cmd_delete(self, interaction: discord.Interaction) -> None: ...
        async def set_lang_callback(self, interaction: discord.Interaction, lang: str) -> None: ...
        async def send_info(self, interaction: discord.Interaction) -> None: ...
        async def handle_login_modal(self, interaction: discord.Interaction) -> None: ...
        async def handle_register_modal(self, interaction: discord.Interaction) -> None: ...
        async def handle_bonus_modal(self, interaction: discord.Interaction) -> None: ...
        async def handle_delete_modal(self, interaction: discord.Interaction) -> None: ...
        async def handle_name_modal(self, interaction: discord.Interaction) -> None: ...
        async def handle_login_change_modal(self, interaction: discord.Interaction) -> None: ...
        async def handle_pass_change_modal(self, interaction: discord.Interaction) -> None: ...
        async def open_name_modal(self, interaction: discord.Interaction) -> None: ...
        async def open_login_modal(self, interaction: discord.Interaction) -> None: ...
        async def open_pass_modal(self, interaction: discord.Interaction) -> None: ...
        async def open_fingerprint_menu(self, interaction: discord.Interaction) -> None: ...
        async def apply_fingerprint(self, interaction: discord.Interaction, fingerprint: str) -> None: ...
        async def confirm_logout(self, interaction: discord.Interaction) -> None: ...
        async def confirm_reset(self, interaction: discord.Interaction) -> None: ...
        async def render_chart(self, interaction: discord.Interaction, days: int) -> None: ...
else:
    class PublicFeatureMixin:
        """Runtime-neutral base for public Discord feature mixins."""
